// @generated by atakit-zk-build because this Program Crate was missing its guest entrypoint wrapper.
// You may edit this file.

#![no_main]

atakit_zk_guest::entrypoint!(program_verifier::AtakitZkGuestProgram);
